version: '3'
services:
  apache:
    build: .docker/apache
    container_name: ${PROJECT_NAME}_apache
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled:delegated
      - ./web:/home/wwwroot/${PROJECT_NAME}:delegated
    links:
      - php
      - database
  database:
    image: mariadb
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - 3306:3306
    volumes:
      - .docker/data/db:/var/lib/mysql:delegated
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  php:
    build: .
    container_name: duplicare_php
    volumes:
      - ./web:/home/wwwroot/${PROJECT_NAME}:delegated
    links:
      - database
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"
  redis:
    image: 'bitnami/redis:latest'
    container_name: ${PROJECT_NAME}_redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .docker/data/redis:/bitnami:delegated
