researchers:
  - title: Naam onderzoeker
    function: "Functie"
    avatar:
      src: "/themes/custom/ama/src/images/placeholders/author.png"
      alt: ""
  - title: Naam onderzoeker
    function: "Functie"
    avatar:
      src: "/themes/custom/ama/src/images/placeholders/author.png"
      alt: ""
  - title: Naam onderzoeker
    function: "Functie"
    avatar:
      src: "/themes/custom/ama/src/images/placeholders/author.png"
      alt: ""
  - title: Naam onderzoeker
    function: "Functie"
    avatar:
      src: "/themes/custom/ama/src/images/placeholders/author.png"
      alt: ""
  - title: Naam onderzoeker
    function: "Functie"
    avatar:
      src: "/themes/custom/ama/src/images/placeholders/author.png"
      alt: ""
  - title: Naam onderzoeker
    function: "Functie"
    avatar:
      src: "/themes/custom/ama/src/images/placeholders/author.png"
      alt: ""