<?php 
use Symfony\Component\Yaml\Parser;

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function drupal_devel_preprocess_html(array &$variables) 
{
    //load yaml files in 
    $configs = _loadYamlConfigs();
    $variables['configs']= $configs;
}


function drupal_devel_preprocess(array &$variables) {

    //load yaml files in 
    $configs = _loadYamlConfigs();
    $variables = array_merge($configs, $variables);
}


/**
 * Implements hook_theme().
 */
function drupal_devel_theme($existing, $type, $theme, $path) {
    return [
      'fe-template' => [
            'variables' => [
                'fe_template' => NULL
            ],
            'template' => 'test-template'
        ],
    ];
  }

  function _loadYamlConfigs() {

    $configs = [];

    global $theme;
    global $base_path;
    $path = drupal_get_path('theme', 'ama');
    $files = glob($path . "/templates/components/config/*.yaml");
    $parser = new Parser();

    foreach($files as $file) {
        $configs = array_merge($configs, $parser->parse(file_get_contents($file)));
    }

    return $configs;
  }